version: '3.8'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=calendarPP'
      - 'MYSQL_ROOT_PASSWORD=mysql'
    networks:
      - internal_network
  backend:
    image: plgr229/calendar-backend:latest
    environment:
        - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/calendarPP'
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - internal_network
networks:
  internal_network: